name: Deploy Infrastructure Workflow using OIDC Authentication
 
on:
  push:
    branches:
      - main
 
permissions:
  id-token: write
  contents: write
  actions: write
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
         role-to-assume: arn:aws:iam::442426854264:role/gaurav_poc
         aws-region: us-east-2  
         web-identity-token-file: ${{ github.event.workflow_run.pull_requests.head.sha }}
 
 
      - name: Terraform Init
        run: terraform init -reconfigure
 
      - name: Terraform Plan
        run: terraform plan
 
      - name: Terraform Apply
        run: terraform apply -auto-approve
 
      # - name: Terraform Refresh
      #   run: terraform refresh
 
      # - name: Terraform Destroy  
      #   run: terraform destroy -auto-approve
